# -*- coding: utf-8 -*-
"""premierLeague_scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xT4xu_nJ9uo2InNFUZCQv5PirYejLky
"""

from io import StringIO
import pandas as pd
from bs4 import BeautifulSoup
import requests
import time

standings_url ="https://fbref.com/en/comps/9/Premier-League-Stats"

import time
yearRange = list(range(2025, 2015, -1))
every_match = [] # each element is a dataframe for a specific team to make
                  # a bigger dataframe of all the teams

#Get every season link for our time range
for year in yearRange:
    data = requests.get(standings_url)
    soup = BeautifulSoup(data.text)
    #First column of the table has links to every team
    standings_table = soup.select('table.stats_table')[0]
    time.sleep(7)
    indivTeamLink = [l.get("href") for l in standings_table.find_all('a')]
    indivTeamLink = [l for l in indivTeamLink if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in indivTeamLink]


    #Setup link to go to the previous season
    previous_season = soup.select("a.prev")[0].get("href")
    standings_url = f"https://fbref.com{previous_season}"

    for team_url in team_urls:
      # Get the team name
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
        data = requests.get(team_url)
      # Get all the match fixture information for that team for that specific season
      # Total of 38 games
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
        soup = BeautifulSoup(data.text)
        indivTeamLink = [l.get("href") for l in soup.find_all('a')]
      # Get shooting stats for the current team for each matchs
        indivTeamLink = [l for l in indivTeamLink if l and 'all_comps/shooting/' in l]
        data = requests.get(f"https://fbref.com{indivTeamLink[0]}")
        time.sleep(7)
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()
      # Merge the two dataframes together for match fixture information and shooting data
        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist","PK", "PKatt"]], on="Date")
        except ValueError:
            continue
        team_data = team_data[team_data["Comp"] == "Premier League"]
      # Append the individual dataframe of the team to the list of dfs
        team_data["Season"] = year
        team_data["Team"] = team_name
        every_match.append(team_data)
        time.sleep(7)

match_df = pd.concat(every_match)

match_df.columns = [c.lower() for c in match_df.columns]
#lower case all column titles

from google.colab import files
match_df = match_df.sort_values('date')
match_df.to_csv("combined_matches_2025-25_to_2015-16.csv")

download = files.download('combined_matches_2025-25_to_2015-16.csv')